package dk.spilpind.stickcalendar

import kotlinx.datetime.DayOfWeek
import kotlinx.datetime.LocalDate
import kotlinx.datetime.Month
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFails

class HolidayFinderTest {

    /**
     * This is made with help from this site: assa.org.au/edm
     */
    private val easterDayMap = listOf(
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1583),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1584),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1585),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1586),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1587),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1588),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1589),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1590),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1591),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1592),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1593),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1594),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1595),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1596),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1597),
        LocalDate(dayOfMonth = 22, month = Month.MARCH, year = 1598),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1599),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1600),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1601),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1602),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1603),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1604),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1605),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1606),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1607),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1608),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1609),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1610),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1611),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1612),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1613),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1614),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1615),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1616),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1617),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1618),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1619),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1620),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1621),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1622),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1623),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1624),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1625),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1626),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1627),
        LocalDate(dayOfMonth = 23, month = Month.APRIL, year = 1628),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1629),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1630),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 1631),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1632),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1633),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1634),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1635),
        LocalDate(dayOfMonth = 23, month = Month.MARCH, year = 1636),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1637),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1638),
        LocalDate(dayOfMonth = 24, month = Month.APRIL, year = 1639),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1640),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1641),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 1642),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1643),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1644),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1645),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1646),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1647),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1648),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1649),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1650),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 1651),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1652),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1653),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1654),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 1655),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1656),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1657),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1658),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1659),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 1660),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1661),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 1662),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 1663),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1664),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1665),
        LocalDate(dayOfMonth = 25, month = Month.APRIL, year = 1666),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1667),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1668),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1669),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1670),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1671),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1672),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1673),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 1674),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1675),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1676),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1677),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1678),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1679),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1680),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1681),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1682),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1683),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1684),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1685),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1686),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1687),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1688),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1689),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1690),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1691),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1692),
        LocalDate(dayOfMonth = 22, month = Month.MARCH, year = 1693),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1694),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1695),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1696),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1697),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1698),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1699),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1700),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1701),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1702),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1703),
        LocalDate(dayOfMonth = 23, month = Month.MARCH, year = 1704),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1705),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1706),
        LocalDate(dayOfMonth = 24, month = Month.APRIL, year = 1707),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1708),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1709),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 1710),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1711),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1712),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1713),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1714),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1715),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1716),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 1717),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1718),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 1719),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1720),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1721),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1722),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 1723),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1724),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1725),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1726),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1727),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 1728),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1729),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 1730),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 1731),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1732),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1733),
        LocalDate(dayOfMonth = 25, month = Month.APRIL, year = 1734),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1735),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1736),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1737),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1738),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1739),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1740),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1741),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 1742),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1743),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1744),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1745),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1746),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1747),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1748),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1749),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1750),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1751),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1752),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1753),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1754),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1755),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1756),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1757),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1758),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1759),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1760),
        LocalDate(dayOfMonth = 22, month = Month.MARCH, year = 1761),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1762),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1763),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1764),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1765),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1766),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1767),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1768),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1769),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1770),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1771),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1772),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1773),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1774),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1775),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1776),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1777),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1778),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1779),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1780),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1781),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1782),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 1783),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1784),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1785),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1786),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1787),
        LocalDate(dayOfMonth = 23, month = Month.MARCH, year = 1788),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1789),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1790),
        LocalDate(dayOfMonth = 24, month = Month.APRIL, year = 1791),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1792),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1793),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 1794),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1795),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1796),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1797),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1798),
        LocalDate(dayOfMonth = 24, month = Month.MARCH, year = 1799),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1800),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1801),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1802),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1803),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1804),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1805),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1806),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1807),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1808),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1809),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1810),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1811),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1812),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1813),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1814),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1815),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1816),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1817),
        LocalDate(dayOfMonth = 22, month = Month.MARCH, year = 1818),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1819),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1820),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1821),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1822),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1823),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1824),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1825),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1826),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1827),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1828),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1829),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1830),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1831),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1832),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1833),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1834),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1835),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1836),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1837),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1838),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1839),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1840),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1841),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1842),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1843),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1844),
        LocalDate(dayOfMonth = 23, month = Month.MARCH, year = 1845),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1846),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1847),
        LocalDate(dayOfMonth = 23, month = Month.APRIL, year = 1848),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1849),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1850),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 1851),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1852),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1853),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1854),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1855),
        LocalDate(dayOfMonth = 23, month = Month.MARCH, year = 1856),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1857),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1858),
        LocalDate(dayOfMonth = 24, month = Month.APRIL, year = 1859),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1860),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1861),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 1862),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1863),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1864),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1865),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1866),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1867),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1868),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 1869),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1870),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 1871),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1872),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1873),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1874),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 1875),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1876),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1877),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1878),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1879),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 1880),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1881),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 1882),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 1883),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1884),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1885),
        LocalDate(dayOfMonth = 25, month = Month.APRIL, year = 1886),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1887),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1888),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1889),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1890),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1891),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1892),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1893),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 1894),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1895),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1896),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1897),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1898),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1899),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1900),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1901),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1902),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1903),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1904),
        LocalDate(dayOfMonth = 23, month = Month.APRIL, year = 1905),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1906),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1907),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1908),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1909),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1910),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1911),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1912),
        LocalDate(dayOfMonth = 23, month = Month.MARCH, year = 1913),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1914),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1915),
        LocalDate(dayOfMonth = 23, month = Month.APRIL, year = 1916),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1917),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1918),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 1919),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1920),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1921),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1922),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1923),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 1924),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1925),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1926),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1927),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 1928),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1929),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 1930),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1931),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 1932),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1933),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1934),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1935),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1936),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 1937),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1938),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 1939),
        LocalDate(dayOfMonth = 24, month = Month.MARCH, year = 1940),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1941),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1942),
        LocalDate(dayOfMonth = 25, month = Month.APRIL, year = 1943),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 1944),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1945),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1946),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1947),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 1948),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1949),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 1950),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 1951),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 1952),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 1953),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1954),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1955),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 1956),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 1957),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1958),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1959),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 1960),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1961),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1962),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1963),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1964),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1965),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1966),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1967),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1968),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1969),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 1970),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1971),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 1972),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1973),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 1974),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1975),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 1976),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 1977),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1978),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1979),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 1980),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1981),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1982),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1983),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 1984),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1985),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1986),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1987),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1988),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 1989),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 1990),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 1991),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 1992),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 1993),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 1994),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 1995),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 1996),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 1997),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 1998),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 1999),
        LocalDate(dayOfMonth = 23, month = Month.APRIL, year = 2000),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2001),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2002),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2003),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2004),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 2005),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2006),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 2007),
        LocalDate(dayOfMonth = 23, month = Month.MARCH, year = 2008),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2009),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2010),
        LocalDate(dayOfMonth = 24, month = Month.APRIL, year = 2011),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 2012),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2013),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2014),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2015),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 2016),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2017),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2018),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2019),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2020),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2021),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2022),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2023),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2024),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2025),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2026),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 2027),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2028),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2029),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2030),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 2031),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 2032),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2033),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2034),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 2035),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 2036),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2037),
        LocalDate(dayOfMonth = 25, month = Month.APRIL, year = 2038),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2039),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2040),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2041),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2042),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 2043),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2044),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2045),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 2046),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2047),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2048),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 2049),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2050),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 2051),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2052),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2053),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 2054),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 2055),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 2056),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 2057),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2058),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2059),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 2060),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2061),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2062),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2063),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2064),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 2065),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2066),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2067),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 2068),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2069),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2070),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2071),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2072),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2073),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2074),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 2075),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2076),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2077),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2078),
        LocalDate(dayOfMonth = 23, month = Month.APRIL, year = 2079),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 2080),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2081),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2082),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2083),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2084),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2085),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2086),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2087),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2088),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2089),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2090),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 2091),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2092),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2093),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2094),
        LocalDate(dayOfMonth = 24, month = Month.APRIL, year = 2095),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2096),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2097),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2098),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2099),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 2100),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2101),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2102),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 2103),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 2104),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2105),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 2106),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2107),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2108),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2109),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2110),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 2111),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2112),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 2113),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 2114),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2115),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 2116),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 2117),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2118),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2119),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2120),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2121),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 2122),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2123),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 2124),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 2125),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2126),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2127),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 2128),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2129),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2130),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2131),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2132),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2133),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2134),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2135),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 2136),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 2137),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2138),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2139),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2140),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2141),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2142),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2143),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2144),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2145),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2146),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2147),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 2148),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2149),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2150),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2151),
        LocalDate(dayOfMonth = 23, month = Month.APRIL, year = 2152),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2153),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2154),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2155),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2156),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 2157),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2158),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 2159),
        LocalDate(dayOfMonth = 23, month = Month.MARCH, year = 2160),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2161),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2162),
        LocalDate(dayOfMonth = 24, month = Month.APRIL, year = 2163),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 2164),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2165),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2166),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2167),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 2168),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2169),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2170),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2171),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2172),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2173),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2174),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2175),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2176),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2177),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2178),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 2179),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2180),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2181),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2182),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 2183),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 2184),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2185),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2186),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 2187),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 2188),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2189),
        LocalDate(dayOfMonth = 25, month = Month.APRIL, year = 2190),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2191),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2192),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2193),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2194),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 2195),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2196),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2197),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 2198),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2199),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2200),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2201),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2202),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2203),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 2204),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 2205),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2206),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2207),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2208),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2209),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2210),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2211),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2212),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2213),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 2214),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2215),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 2216),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2217),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2218),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2219),
        LocalDate(dayOfMonth = 23, month = Month.APRIL, year = 2220),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2221),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2222),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2223),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2224),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 2225),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2226),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 2227),
        LocalDate(dayOfMonth = 23, month = Month.MARCH, year = 2228),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2229),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2230),
        LocalDate(dayOfMonth = 24, month = Month.APRIL, year = 2231),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 2232),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2233),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2234),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2235),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 2236),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2237),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2238),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2239),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2240),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2241),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2242),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2243),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2244),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 2245),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2246),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 2247),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2248),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2249),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2250),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 2251),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 2252),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2253),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2254),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 2255),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 2256),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2257),
        LocalDate(dayOfMonth = 25, month = Month.APRIL, year = 2258),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2259),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2260),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2261),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2262),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 2263),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2264),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 2265),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 2266),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2267),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2268),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 2269),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2270),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 2271),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2272),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2273),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 2274),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 2275),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 2276),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 2277),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2278),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2279),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 2280),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2281),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2282),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2283),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2284),
        LocalDate(dayOfMonth = 22, month = Month.MARCH, year = 2285),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2286),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2287),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 2288),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 2289),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2290),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2291),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2292),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2293),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2294),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 2295),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2296),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2297),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2298),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2299),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 2300),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2301),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2302),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2303),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 2304),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2305),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2306),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2307),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2308),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 2309),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2310),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2311),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2312),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 2313),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2314),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 2315),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2316),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2317),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2318),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2319),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 2320),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2321),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2322),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 2323),
        LocalDate(dayOfMonth = 13, month = Month.APRIL, year = 2324),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2325),
        LocalDate(dayOfMonth = 25, month = Month.APRIL, year = 2326),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2327),
        LocalDate(dayOfMonth = 1, month = Month.APRIL, year = 2328),
        LocalDate(dayOfMonth = 21, month = Month.APRIL, year = 2329),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2330),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 2331),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2332),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 2333),
        LocalDate(dayOfMonth = 25, month = Month.MARCH, year = 2334),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2335),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2336),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 2337),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2338),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2339),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2340),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2341),
        LocalDate(dayOfMonth = 29, month = Month.MARCH, year = 2342),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2343),
        LocalDate(dayOfMonth = 2, month = Month.APRIL, year = 2344),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 2345),
        LocalDate(dayOfMonth = 14, month = Month.APRIL, year = 2346),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2347),
        LocalDate(dayOfMonth = 18, month = Month.APRIL, year = 2348),
        LocalDate(dayOfMonth = 10, month = Month.APRIL, year = 2349),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2350),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2351),
        LocalDate(dayOfMonth = 6, month = Month.APRIL, year = 2352),
        LocalDate(dayOfMonth = 22, month = Month.MARCH, year = 2353),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2354),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2355),
        LocalDate(dayOfMonth = 22, month = Month.APRIL, year = 2356),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 2357),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2358),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2359),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2360),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2361),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2362),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2363),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2364),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2365),
        LocalDate(dayOfMonth = 3, month = Month.APRIL, year = 2366),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2367),
        LocalDate(dayOfMonth = 7, month = Month.APRIL, year = 2368),
        LocalDate(dayOfMonth = 30, month = Month.MARCH, year = 2369),
        LocalDate(dayOfMonth = 19, month = Month.APRIL, year = 2370),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2371),
        LocalDate(dayOfMonth = 26, month = Month.MARCH, year = 2372),
        LocalDate(dayOfMonth = 15, month = Month.APRIL, year = 2373),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2374),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2375),
        LocalDate(dayOfMonth = 11, month = Month.APRIL, year = 2376),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 2377),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2378),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 2379),
        LocalDate(dayOfMonth = 23, month = Month.MARCH, year = 2380),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2381),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2382),
        LocalDate(dayOfMonth = 24, month = Month.APRIL, year = 2383),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 2384),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2385),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2386),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2387),
        LocalDate(dayOfMonth = 27, month = Month.MARCH, year = 2388),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2389),
        LocalDate(dayOfMonth = 8, month = Month.APRIL, year = 2390),
        LocalDate(dayOfMonth = 24, month = Month.MARCH, year = 2391),
        LocalDate(dayOfMonth = 12, month = Month.APRIL, year = 2392),
        LocalDate(dayOfMonth = 4, month = Month.APRIL, year = 2393),
        LocalDate(dayOfMonth = 17, month = Month.APRIL, year = 2394),
        LocalDate(dayOfMonth = 9, month = Month.APRIL, year = 2395),
        LocalDate(dayOfMonth = 31, month = Month.MARCH, year = 2396),
        LocalDate(dayOfMonth = 20, month = Month.APRIL, year = 2397),
        LocalDate(dayOfMonth = 5, month = Month.APRIL, year = 2398),
        LocalDate(dayOfMonth = 28, month = Month.MARCH, year = 2399),
        LocalDate(dayOfMonth = 16, month = Month.APRIL, year = 2400),
    ).map { date -> date.year to date }.toMap()

    private val expectedFirstYear = easterDayMap.keys.minOrNull() ?: 0
    private val lastStaticYear = easterDayMap.keys.maxOrNull() ?: 0

    @Test
    fun easterCheckWeekDay() {
        (expectedFirstYear..10000).forEach { year ->
            assertEquals(expected = DayOfWeek.SUNDAY, HolidayFinder.findEaster(year).dayOfWeek)
        }
    }

    @Test
    fun easterCheckDateStatic() {
        (expectedFirstYear..lastStaticYear).forEach { year ->
            assertEquals(expected = easterDayMap[year], HolidayFinder.findEaster(year))
        }
    }

    @Test
    fun easterCheckDynamic() {
        (lastStaticYear + 1..4099).forEach { year ->
            assertEquals(expected = calculateDateWithAssa(year), HolidayFinder.findEaster(year))
        }
    }

    @Test
    fun easterCheckMinimumSupportedYear() {
        assertFails {
            HolidayFinder.findEaster(expectedFirstYear - 1)
        }
    }

    @Test
    fun pentecostCheckWeekDay() {
        (expectedFirstYear..10000).forEach { year ->
            assertEquals(expected = DayOfWeek.SUNDAY, HolidayFinder.findPentecost(year).dayOfWeek)
        }
    }

    @Test
    fun pentecostCheckDateStatic() {
        val expectedPentecostDates = listOf(
            LocalDate(dayOfMonth = 29, month = Month.MAY, year = 1583),
            LocalDate(dayOfMonth = 21, month = Month.MAY, year = 1600),
            LocalDate(dayOfMonth = 3, month = Month.JUNE, year = 1900),
            LocalDate(dayOfMonth = 31, month = Month.MAY, year = 2020),
            LocalDate(dayOfMonth = 23, month = Month.MAY, year = 2021),
            LocalDate(dayOfMonth = 5, month = Month.JUNE, year = 2022),
            LocalDate(dayOfMonth = 4, month = Month.JUNE, year = 2400),
        )

        expectedPentecostDates.forEach { expectedDate ->
            assertEquals(expected = expectedDate, HolidayFinder.findPentecost(expectedDate.year))
        }
    }

    /**
     * Logic from assa.org.au/edm which also generated some of the static map, but are here to help with the remaining
     * dates that we don't want to have statically
     */
    private fun calculateDateWithAssa(year: Int): LocalDate {
        val firstDigits = year / 100
        val lastDigits = year % 100
        val remainder19 = year % 19

        // Calculate PFM (Paschal Full Moon) date
        var temp = (firstDigits - 15) / 2 + 202 - (11 * remainder19)

        when (firstDigits) {
            21, 24, 25, 27, 28, 29, 30, 31, 32, 34, 35, 38 ->
                temp -= 1
            33, 36, 37, 39, 40 ->
                temp -= 2
        }
        temp %= 30

        var tableA = temp + 21
        if (temp == 29) {
            tableA -= 1
        }
        if (temp == 28 && remainder19 > 10) {
            tableA -= 1
        }

        // Find the next Sunday
        val tableB = (tableA - 19) % 7

        var tableC = (40 - firstDigits) % 4
        if (tableC == 3) {
            tableC += 1
        }
        if (tableC > 1) {
            tableC += 1
        }

        val tableD = (lastDigits + (lastDigits / 4)) % 7

        val tableE = ((20 - tableB - tableC - tableD) % 7) + 1
        val dayOfMarch = tableA + tableE

        return if (dayOfMarch > 31) {
            LocalDate(dayOfMonth = dayOfMarch - 31, month = Month.APRIL, year = year)
        } else {
            LocalDate(dayOfMonth = dayOfMarch, month = Month.MARCH, year = year)
        }
    }
}
